version: '3.8'

services:
  xray-bot:
    build: .
    container_name: xray-telegram-bot
    restart: unless-stopped
    volumes:
      - ./xray_bot.py:/app/xray_bot.py
      - ../xray-reality/scripts:/app/scripts
      - ../xray-reality/stats:/app/stats
      - ../xray-reality/config.json:/app/config.json
    depends_on:
      - xray-reality
    environment:
      - TZ=Europe/Moscow
    networks:
      - xray-network

networks:
  xray-network:
    external: true
    name: xray-reality_xray-network
