version: '3.8'

services:
  xray-reality:
    image: teddysun/xray:latest
    container_name: xray-reality
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./config.json:/etc/xray/config.json
      - ./logs:/var/log/xray
      - ./stats:/opt/xray/stats
    networks:
      - xray-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:10085/stats"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  xray-network:
    driver: bridge
